---
driver:
  name: vagrant
  provider: virtualbox
  gui: true
  username: vagrant
  password: vagrant
  elevated: false
  elevated_username: vagrant
  elevated_password: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14

platforms:
  - name: windows-2012R2
    transport:
      name: winrm
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[test_archive]
