---
driver:
  name: vagrant
  provider: virtualbox
  gui: true
  username: vagrant
  password: vagrant
  elevated: false
  elevated_username: vagrant
  elevated_password: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[test_archive]
