---
driver:
  name: vagrant
  provider: virtualbox
  gui: true
  username: vagrant
  password: vagrant
  elevated: false
  elevated_username: vagrant
  elevated_password: vagrant

provisioner:
  product_name: chef
  deprecations_as_errors: true
  enforce_idempotency: true
  multiple_converge: 2
  product_version: 13.8.5
  install_strategy: once

platforms:
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[test_archive]
