name             'seven_zip'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures 7-Zip'
version          '3.2.0'
source_url       'https://github.com/sous-chefs/seven_zip'
issues_url       'https://github.com/sous-chefs/seven_zip/issues'
chef_version     '>= 13.0'

supports         'windows'
depends          'windows'
