name             'seven_zip'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
issues_url       'https://github.com/windowschefcookbooks/seven_zip/issues'
source_url       'https://github.com/windowschefcookbooks/seven_zip'
license          'Apache 2.0'
description      'Installs/Configures the 7-zip file archiver'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '2.0.2'
supports         'windows'
depends          'windows', '>= 1.2.2'
