name             'seven_zip'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/seven_zip'
issues_url       'https://github.com/windowschefcookbooks/seven_zip/issues'
chef_version     '>= 14.0'
license          'Apache-2.0'
description      'Installs/Configures 7-Zip'
version          '4.0.0'
supports         'windows'
